inrupt/solid-client-java

.github/workflows/nvd-cache.yml
[Version 6.0.0](https://github.com/jeremylong/Open-Vulnerability-Project/releases/tag/v6.0.0) of the Open Vulnerability Project was released a few weeks ago. This updates our use of that project.
=> Upgrade the vulnz version to 6.0.0

examples/springboot/pom.xml
The SpringBoot example code brings in a vulnerable version of `com.nimbusds:nimbus-jose-jwt` via `org.springframework.security/spring-security-oauth2-jose@6.2.3`.
This upgrades to the latest version of `nimbus-jose-jwt`
=> Upgrade Nimbus JWT library in SpringBoot example

integration/pom.xml, performance/pom.xml, pom.xml
The maven configuration could be cleaned up a bit, including using the non-deprecated license plugin structure as well as being consistent with our use of PMD (i.e. turning off warnings for test code)
=> Clean up maven configuration

api/src/main/java/com/inrupt/client/ProblemDetails.java, api/src/main/java/com/inrupt/client/Response.java, solid/src/main/java/com/inrupt/client/solid/SolidClient.java, solid/src/main/java/com/inrupt/client/solid/SolidClientException.java, solid/src/test/java/com/inrupt/client/solid/SolidClientTest.java
This is based on #1160, which should be reviewed first.
The `SolidClient` now uses the `throwOnError` body mapper to handle error responses, and provides a custom exception mapper to throw the appropriate specialized exception.
=> JCL-402: Low-level client throws enriched exceptions

jena/pom.xml, jena/src/main/java/com/inrupt/client/jena/JenaBodyHandlers.java, jena/src/test/java/com/inrupt/client/jena/JenaBodyHandlersTest.java, test/src/main/java/com/inrupt/client/test/RdfMockService.java
This is based on #1160, which should be reviewed first.
This deprecates the current methods in `JenaBodyHandlers`, and replaces them with similar method throwing an appropriate exception with error details on HTTP error instead of returning an empty dataset. This makes use of the composable throwing body handler now exposed by the `Response` interface of the `api` module. The new method now have `Jena` in their name for this not to be a breaking change: `ofModel` becomes `ofJenaModel`, etc.
=> JCL-402: HTTP error handling in JenaBodyHandlers

jena/src/main/java/com/inrupt/client/jena/JenaBodyHandlers.java, jena/src/test/java/com/inrupt/client/jena/JenaBodyHandlersTest.java, rdf4j/src/main/java/com/inrupt/client/rdf4j/RDF4JBodyHandlers.java, rdf4j/src/test/java/com/inrupt/client/rdf4j/RDF4JBodyHandlersTest.java
This is based on #1159 , which should be reviewed first. (The only dependency between the two is in the mocks)
This deprecates the current methods in `RDF4JBodyHandlers`, and replaces them with similar method throwing an appropriate exception with error details on HTTP error instead of returning an empty dataset. This makes use of the composable throwing body handler now exposed by the `Response` interface of the `api` module. The new method now have `RDF4J` in their name for this not to be a breaking change: `ofModel` becomes `ofRDF4JModel`, etc.
=> JCL-402: RDF4J body handlers http error handling

bom/pom.xml
The BOM previously included okhttp (since Quarkus' BOM included a much older version of that), but that is generally not needed any longer, and it is better to avoid listing too many transitive dependencies, since BOMs are often layered
=> Clean up BOM definitions

examples/cli/pom.xml, examples/webapp/pom.xml, quarkus/pom.xml
This changes to groupId to `io.quarkus.platform` for Quarkus version management
=> Use quarkus platform version

openid/src/main/java/com/inrupt/client/openid/Metadata.java, openid/src/main/java/com/inrupt/client/openid/OpenIdProvider.java, openid/src/main/java/com/inrupt/client/openid/OpenIdSession.java, openid/src/main/java/com/inrupt/client/openid/TokenRequest.java, openid/src/test/java/com/inrupt/client/openid/OpenIdMockHttpService.java, openid/src/test/java/com/inrupt/client/openid/OpenIdProviderTest.java, openid/src/test/resources/metadata.json
This improves support for RFC 9270 for anyone building an authorization code flow client with the JCL API.
=> JCL-444: Improve support for RFC 9207

examples/pom.xml, examples/spring-web/pom.xml, examples/spring-web/src/main/java/com/inrupt/client/examples/spring/web/SecurityConfiguration.java, examples/spring-web/src/main/java/com/inrupt/client/examples/spring/web/WebApplication.java, examples/spring-web/src/main/java/com/inrupt/client/examples/spring/web/controller/SolidController.java, examples/spring-web/src/main/java/com/inrupt/client/examples/spring/web/model/Profile.java, examples/spring-web/src/main/java/com/inrupt/client/examples/spring/web/model/Resource.java, examples/spring-web/src/main/java/com/inrupt/client/examples/spring/web/model/WebId.java, examples/spring-web/src/main/resources/application.yml, examples/spring-web/src/main/resources/static/assets/script.js, examples/spring-web/src/main/resources/static/index.html, examples/spring-web/src/main/resources/templates/error.html, examples/spring-web/src/test/java/com/inrupt/client/examples/spring/web/MockWebServer.java, examples/spring-web/src/test/java/com/inrupt/client/examples/spring/web/WebApplicationTests.java, examples/spring-web/src/test/resources/testKey.json
This adds another Spring-based example application. This application does not currently have any CSS styling to speak of, but the Spring API portion uses recommended, idiomatic constructs.
=> Add Spring example with authentication

examples/pom.xml
The CD task that builds the javadoc site fails because the Spring boot examples use newer Java 17 constructs (SpringBoot 3 requires Java 17). Since the example code doesn't need to be included in the generated site, this PR just excludes everything in the `/examples` directory
=> Fix site build failures

openid/src/main/java/com/inrupt/client/openid/OpenIdProvider.java, openid/src/test/java/com/inrupt/client/openid/OpenIdProviderTest.java
Addresses #1374 
This adds support for some missing parameters in the authorization code flow, in particular `scope`, `state` and `nonce`.
=> JCL-469: Add support for scope, state and nonce values in OpenIdProvider::authorize

openid/src/main/java/com/inrupt/client/openid/OpenIdProvider.java, openid/src/test/java/com/inrupt/client/openid/OpenIdProviderTest.java
=> JCL-469: Add support for scope, state and nonce values in the OpenIdProvider

pom.xml
For Java 11 test runs, Spring security is pinned to the latest 5.x version, but that isn't managed by dependabot, so it needs to be manually updated.
=> Bump spring security version for Java 11 testing

integration/pom.xml, performance/pom.xml
For modules that are not deployed, there is no need to generate javadocs; they only fill the CI output with warnings.
=> Turn off javadoc generation for non-deployed artifacts

access-grant/pom.xml, api/pom.xml, api/src/main/java/com/inrupt/client/ProblemDetails.java, core/pom.xml, examples/cli/pom.xml, examples/spring-web/pom.xml, examples/springboot/pom.xml, examples/webapp/pom.xml, okhttp/pom.xml, openid/pom.xml, parser/pom.xml, pom.xml, quarkus/pom.xml, rdf-legacy/pom.xml, rdf4j/pom.xml, solid/pom.xml, solid/src/main/java/com/inrupt/client/solid/SolidClientException.java, solid/src/main/java/com/inrupt/client/solid/SolidProblemDetails.java, solid/src/test/java/com/inrupt/client/solid/SolidClientTest.java, solid/src/test/java/com/inrupt/client/solid/SolidProblemDetailsTest.java, spring/pom.xml, uma/pom.xml
There are three significant changes to the ProblemsDetails API in this PR:
* `ProblemDetails::getDetails` becomes `ProblemDetails::getDetail`. This aligns the implementation with the RFC
* The `ProblemDetails.DEFAULT_TYPE` value is now a `URI` (instead of a `String`)
* `SolidClientException::fromErrorResponse` has been refactored.
* The autocloseable `InputStream` is now handled in a try-with-resources block to prevent resource leakage
* The method accepts a response `URI` so that any relative `URI`s in the `ProblemDetails` body can be resolved correctly
* The method is made package-private, since it is not used outside of the package and I don't see a reason to make it part of the public API
* The logic has been reworked to remove duplication and simplify the flow considerably
In …
=> JCL-476: Adjust ProblemDetails API

.github/workflows/ci-config.yml, integration/base/src/main/java/com/inrupt/client/integration/base/AccessGrantScenarios.java, integration/base/src/main/java/com/inrupt/client/integration/base/ApplicationRequestMetadataScenarios.java, integration/base/src/main/java/com/inrupt/client/integration/base/AuthenticationScenarios.java, integration/base/src/main/java/com/inrupt/client/integration/base/DomainModulesResource.java, integration/base/src/main/java/com/inrupt/client/integration/base/MockUMAAuthorizationServer.java, integration/base/src/main/java/com/inrupt/client/integration/base/SolidServerTransformer.java, integration/base/src/main/java/com/inrupt/client/integration/base/Utils.java
This adds the ProblemDetails checks to the integration testing framework.
The challenge is that, when testing against a live ESS server, there are some versions that already support ProblemDetails responses and others that don't. So this code needs to be able to check based on the capability of the server.
=> JCL-476: problem details integration tests

.github/workflows/ci-config.yml, integration/base/src/main/java/com/inrupt/client/integration/base/AccessGrantScenarios.java, integration/base/src/main/java/com/inrupt/client/integration/base/ApplicationRequestMetadataScenarios.java, integration/base/src/main/java/com/inrupt/client/integration/base/AuthenticationScenarios.java, integration/base/src/main/java/com/inrupt/client/integration/base/DomainModulesResource.java
A configuration value was added to aid in feature detection for server-side `ProblemDetails` support in https://github.com/inrupt/solid-client-java/pull/1395/commits/103339f65ffd37774debdd9a08f22854baee2af3 (and subsequent commits in #1395) and then adjusted in https://github.com/inrupt/solid-client-java/pull/1396.
However, that has caused CD to fail ever since and prevents CI from succeeding.
This removes the configuration value entirely and relies solely on feature detection.
=> Revert feature detection configuration

access-grant/src/main/java/com/inrupt/client/accessgrant/AccessDenial.java, access-grant/src/main/java/com/inrupt/client/accessgrant/AccessGrant.java, access-grant/src/main/java/com/inrupt/client/accessgrant/AccessGrantClient.java, access-grant/src/main/java/com/inrupt/client/accessgrant/AccessRequest.java, access-grant/src/test/java/com/inrupt/client/accessgrant/AccessDenialTest.java, access-grant/src/test/java/com/inrupt/client/accessgrant/AccessGrantTest.java, access-grant/src/test/java/com/inrupt/client/accessgrant/AccessRequestTest.java, access-grant/src/test/resources/access_denial1.json, access-grant/src/test/resources/access_denial2.json, access-grant/src/test/resources/access_grant4.json, access-grant/src/test/resources/access_request3.json, integration/base/src/main/java/com/inrupt/client/integration/base/AccessGrantScenarios.java
At present, the `AccessGrantClient` processes Access Credentials with either the shorter localname (e.g. `SolidAccessGrant`, `SolidAccessRequest`, `SolidAccessDenial`) or the fully qualified name (e.g. `http://www.w3.org/ns/solid/vc#SolidAccessGrant`). There are cases where a qualified name, such as `vc:AccessGrantDenial`, will be returned from an Access Grant server, and these should be supported as well.
Resolves #1407
Specifically, this adds support for qualified type names with the `vc:` prefix across the various Access Grant types. In addition, the testing has been expanded to include better coverage of SolidAccessDenial types.
=> Support qualified type names in the Access Grant client

jena/pom.xml
The default jackson dependency brought in by Jena 4.x is somewhat old. This ensures that the jackson version aligns with the rest of the codebase
=> Update jackson dependencies in Jena module

.github/dependabot.yml, pom.xml
This adjusts the dependabot configuration to group all plugin updates. This should reduce the noise from dependabot updates across the various supported branches.
=> Consolidate dependabot management

archetypes/java/src/main/resources/META-INF/maven/archetype-metadata.xml, archetypes/java/src/main/resources/archetype-resources/pom.xml, archetypes/java/src/test/resources/projects/test/archetype.properties
The archetype plugin versions were getting out of sync with the rest of the project. Also, it was using Java 11, which is somewhat old and incompatible with most big frameworks.
=> Align archetype plugin versions with project

pom.xml
For Java 11 support, we use Spring Security 5.x. This updates the version of spring-security for Java 11 runtimes.
=> Update spring security version

.github/dependabot.yml
This also removes dependabot updates on the 1.0 branch, as there are currently no plans to release new versions on that series.
=> Configure dependabot for 1.2 maintenance

pom.xml
This upgrades the default Jena version to 5.x.
For Java 11 runtimes, Jena 4.10.x will still be used.
=> Upgrade to Jena 5

.github/workflows/nvd-cache.yml
This should fix the failing `maven-dependency-check` plugin updates.
=> Upgrade Open Vulnerability Project version

access-grant/src/main/java/com/inrupt/client/accessgrant/AccessCredential.java, access-grant/src/main/java/com/inrupt/client/accessgrant/AccessDenial.java, access-grant/src/main/java/com/inrupt/client/accessgrant/AccessGrant.java, access-grant/src/main/java/com/inrupt/client/accessgrant/AccessGrantClient.java, access-grant/src/test/java/com/inrupt/client/accessgrant/AccessDenialTest.java, access-grant/src/test/java/com/inrupt/client/accessgrant/AccessGrantTest.java, access-grant/src/test/resources/access_denial1.json, access-grant/src/test/resources/access_grant4.json
This creates a link between access grants/denials and the corresponding access request. There is no change to the AccessGrantClient API. For the AccessGrant and AccessDenial classes, there is a new `::getAccessRequest` method.
=> JCL-474: Link access grants and denials to originating requests

.github/dependabot.yml
This updates the dependabot configuration for the 1.3 maintenance branch. Note that this removes the 1.1 maintenance branch from dependabot management.
=> Update dependabot configuration for 1.3 development

.github/workflows/nvd-cache.yml
This updates the gradle build of the open vulnerability project, which is currently failing
=> Update NVD cache generation

integration/base/pom.xml, performance/base/pom.xml, pom.xml, spring/pom.xml
This removes the special profiles from the various submodules and puts the smallrye-config version config in the parent pom profile so that dependabot updates are more manageable for Smallrye Config
=> Update java 11 configuration to include smallrye config

integration/base/pom.xml, performance/base/pom.xml, pom.xml, spring/pom.xml
This is a backport of #1890 
The parent pom does not currently have a Java 11 profile for the 1.2 maintenance branch, so one is added
=> Use shared java 11 profile for SR-config version mgmt

build-tools/owasp/suppressions.xml, spring/pom.xml
This extends the OWASP suppressions that expired recently, to be checked against in three months.
=> Extend OWASP suppressions by three months

build-tools/owasp/suppressions.xml, integration/base/pom.xml, performance/base/pom.xml, pom.xml, test/pom.xml
The OWASP suppression list includes some entries that can be removed by using the stand-alone version of wiremock
=> Remove OWASP suppression configuration

.github/dependabot.yml, pom.xml, rdf4j/pom.xml
This removes some work-arounds that were in place for Java 8/11. They can be removed now that Java 17 is the baseline supported version.
=> JCL-476: Simplify build setup for Java 17
